// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using MyFitnessApp.Api.Data;

#nullable disable

namespace MyFitnessApp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222120000_AddUserFollows")]
    partial class AddUserFollows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyFitnessApp.Api.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("DateOfBirth").HasColumnType("timestamp with time zone");
                    b.Property<string>("DisplayName").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Gender").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<decimal?>("HeightCm").HasPrecision(5, 2).HasColumnType("numeric(5,2)");
                    b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.Property<decimal?>("WeightKg").HasPrecision(5, 2).HasColumnType("numeric(5,2)");
                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<bool>("IsAdmin").HasColumnType("boolean");
                    b.Property<bool>("IsBanned").HasColumnType("boolean");
                    b.Property<string>("NormalizedEmail").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail").IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Category").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.HasKey("Id");
                    b.HasIndex("Name");
                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.Food", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<decimal>("CaloriesPer100g").HasColumnType("numeric(18,2)");
                    b.Property<decimal>("CarbsPer100g").HasColumnType("numeric(18,2)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<decimal>("FatPer100g").HasColumnType("numeric(18,2)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<decimal>("ProteinPer100g").HasColumnType("numeric(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("Name");
                    b.ToTable("Foods");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.Article", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid?>("AuthorUserId").HasColumnType("uuid");
                    b.Property<Guid?>("CategoryId").HasColumnType("uuid");
                    b.Property<string>("Content").IsRequired().HasMaxLength(50000).HasColumnType("character varying(50000)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                    b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("AuthorUserId");
                    b.HasIndex("CategoryId");
                    b.ToTable("Articles");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.ArticleCategory", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.ToTable("ArticleCategories");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.Comment", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Content").IsRequired().HasMaxLength(5000).HasColumnType("character varying(5000)");
                    b.Property<Guid>("PostId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("PostId");
                    b.HasIndex("UserId");
                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.EatingPlan", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("PlanDate").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "PlanDate").IsUnique();
                    b.ToTable("EatingPlans");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.EatingPlanEntry", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("EatingPlanId").HasColumnType("uuid");
                    b.Property<Guid>("FoodId").HasColumnType("uuid");
                    b.Property<decimal>("QuantityGrams").HasColumnType("numeric(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("EatingPlanId");
                    b.HasIndex("FoodId");
                    b.ToTable("EatingPlanEntries");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.ForumPost", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Content").IsRequired().HasMaxLength(10000).HasColumnType("character varying(10000)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                    b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAtUtc");
                    b.HasIndex("UserId");
                    b.ToTable("ForumPosts");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.WorkoutPlan", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("PlanDate").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "PlanDate").IsUnique();
                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.WorkoutPlanEntry", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<int?>("DurationMinutes").HasColumnType("integer");
                    b.Property<Guid>("ExerciseId").HasColumnType("uuid");
                    b.Property<int?>("Reps").HasColumnType("integer");
                    b.Property<int?>("Sets").HasColumnType("integer");
                    b.Property<Guid>("WorkoutPlanId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("ExerciseId");
                    b.HasIndex("WorkoutPlanId");
                    b.ToTable("WorkoutPlanEntries");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.UserFollow", b =>
                {
                    b.Property<Guid>("FollowerUserId").HasColumnType("uuid");
                    b.Property<Guid>("FollowingUserId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.HasKey("FollowerUserId", "FollowingUserId");
                    b.HasIndex("FollowerUserId", "FollowingUserId").IsUnique();
                    b.HasIndex("FollowingUserId");
                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.Profile", b =>
                {
                    b.HasOne("MyFitnessApp.Api.Models.User", "User").WithOne("Profile").HasForeignKey("MyFitnessApp.Api.Models.Profile", "UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.Article", b =>
                {
                    b.HasOne("MyFitnessApp.Api.Models.User", "Author").WithMany().HasForeignKey("AuthorUserId").OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("MyFitnessApp.Api.Models.ArticleCategory", "Category").WithMany("Articles").HasForeignKey("CategoryId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Author");
                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.ArticleCategory", b => { b.Navigation("Articles"); });

            modelBuilder.Entity("MyFitnessApp.Api.Models.Comment", b =>
                {
                    b.HasOne("MyFitnessApp.Api.Models.ForumPost", "Post").WithMany("Comments").HasForeignKey("PostId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("MyFitnessApp.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Post");
                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.EatingPlanEntry", b =>
                {
                    b.HasOne("MyFitnessApp.Api.Models.EatingPlan", "EatingPlan").WithMany("Entries").HasForeignKey("EatingPlanId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("MyFitnessApp.Api.Models.Food", "Food").WithMany().HasForeignKey("FoodId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("EatingPlan");
                    b.Navigation("Food");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.EatingPlan", b =>
                {
                    b.HasOne("MyFitnessApp.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Entries");
                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.ForumPost", b =>
                {
                    b.HasOne("MyFitnessApp.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Comments");
                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.WorkoutPlanEntry", b =>
                {
                    b.HasOne("MyFitnessApp.Api.Models.Exercise", "Exercise").WithMany().HasForeignKey("ExerciseId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("MyFitnessApp.Api.Models.WorkoutPlan", "WorkoutPlan").WithMany("Entries").HasForeignKey("WorkoutPlanId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Exercise");
                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.WorkoutPlan", b =>
                {
                    b.HasOne("MyFitnessApp.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Entries");
                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.UserFollow", b =>
                {
                    b.HasOne("MyFitnessApp.Api.Models.User", "FollowerUser").WithMany().HasForeignKey("FollowerUserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("MyFitnessApp.Api.Models.User", "FollowingUser").WithMany().HasForeignKey("FollowingUserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("FollowerUser");
                    b.Navigation("FollowingUser");
                });

            modelBuilder.Entity("MyFitnessApp.Api.Models.User", b => { b.Navigation("Profile"); });
#pragma warning restore 612, 618
        }
    }
}
